name: Deploy to Cloud

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发工作流

jobs:
  deploy:
    runs-on: ubuntu-latest  # 指定运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码

      - name: Set up Python
        uses: actions/setup-python@v2  # 设置 Python 环境
        with:
          python-version: '3.8'  # 指定 Python 版本

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # 安装依赖

      - name: Run your script
        env:  # 设置环境变量
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}  # 从 GitHub Secrets 中获取
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}  # 从 GitHub Secrets 中获取
        run: |
          python your_script.py  # 运行您的 Python 脚本
